export const ADD_PERSONAL_INFORMATION = "ADD_PERSONAL_INFORMATION"

export const ADD_EDUCATIONAL_DETAILS = "ADD_EDUCATIONAL_DETAILS"

export const ADD_WORK_EXPERIENCE_DETAILS = "ADD_WORK_EXPERIENCE_DETAILS"

export const ADD_SKILLS_AND_QUALIFICATIONS = "ADD_SKILLS_AND_QUALIFICATIONS"

export const ADD_COVER_LETTER_AND_RESUME = "ADD_COVER_LETTER_AND_RESUME"

export const RESET_ALL_REDUCER = "RESET_ALL_REDUCER"